// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO-YmPlPnpX__KQkowoqYoIDIdmWlIfjs',
    appId: '1:62903909022:web:addffb37c4791d0a44598f',
    messagingSenderId: '62903909022',
    projectId: 'baxa-5bab0',
    authDomain: 'baxa-5bab0.firebaseapp.com',
    storageBucket: 'baxa-5bab0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1AIHDUGdjKnj7yhfpFbc_h6vScp_6kJU',
    appId: '1:62903909022:android:eccbc1d9a071d8b044598f',
    messagingSenderId: '62903909022',
    projectId: 'baxa-5bab0',
    storageBucket: 'baxa-5bab0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJJc2UiESmtsSG3GCo8Ms35vsF5RAAqEw',
    appId: '1:62903909022:ios:c685b4cd46423acb44598f',
    messagingSenderId: '62903909022',
    projectId: 'baxa-5bab0',
    storageBucket: 'baxa-5bab0.firebasestorage.app',
    iosBundleId: 'com.domain.baxa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJJc2UiESmtsSG3GCo8Ms35vsF5RAAqEw',
    appId: '1:62903909022:ios:c685b4cd46423acb44598f',
    messagingSenderId: '62903909022',
    projectId: 'baxa-5bab0',
    storageBucket: 'baxa-5bab0.firebasestorage.app',
    iosBundleId: 'com.domain.baxa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO-YmPlPnpX__KQkowoqYoIDIdmWlIfjs',
    appId: '1:62903909022:web:910c5a6ab144266144598f',
    messagingSenderId: '62903909022',
    projectId: 'baxa-5bab0',
    authDomain: 'baxa-5bab0.firebaseapp.com',
    storageBucket: 'baxa-5bab0.firebasestorage.app',
  );
}
